<?php

/**
 * @file
 * Contains import_default_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function import_default_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the import_default_content module.
    case 'help.page.import_default_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module to import default content') . '</p>';
      return $output;

    default:
  }
}